version: "3.9"
services:
  web1:
    build: ./app # use dockerfile in the ./app
    ports:
      - "3001:3000"

  web2:
    build: ./app
    ports:
      - "3002:3000"

  web3:
    build: ./app
    ports:
      - "3003:3000"

